### ISSUE TITLE
[코멘트 요청]

### ISSUE THREAD

**Issue by hayeooooon** [hayeooooon/w4_react#1]
# 코드리뷰 신청 및 질문

<br>

## 질문하게 된 계기
게시글 등록 및 수정 페이지에서 내용 작성 후 등록/수정 버튼을 눌렀을 때,
데이터 추가 및 수정하는 처리가 먼저 완료된 후에 메인 페이지로 이동하는 이벤트를 발생시키고 싶은데
어떤 방식으로 구현하는 것이 올바른 방법인지가 궁금합니다.
동기/비동기 처리 방식에 대해 공부를 했는데도 명확한 답이 안나오는 것을 보니 공부가 더 필요한 것 같아요.. ㅜㅜ

<br/>

### 처음 시도한 코드

```javascript
if (!validation.term && !validation.desc && !validation.exam) {
	dispatch(
		updateTermsFB(this_term.id, {
			term: term,
			desc: description,
			example: example,
			done: this_term.done,
		})
	);
	navigate("/");
}
```
게시글 등록 및 수정 페이지에서, 등록/수정 버튼을 클릭했을 경우 
1. 등록된 데이터나 수정된 데이터를 저장하는 액션을 dispatch
2. 메인페이지로 이동을 시키기 위해 navigate('/') 

위와 같은 방식으로 작성했더니 dispatch로 전달한 데이터추가/데이터수정에 해당하는 action이 navigate보다 나중에 실행되어서,
메인페이지가 먼저 load 되고 데이터 load하는 액션 먼저 발생 > 이후 게시글이 추가되는 액션이 발생되어 똑같은 게시글이 2개 보여지는 현상이 발생하거나, 수정된 내용이 반영이 되지 않는 현상이 발생했습니다.

 <br/>

### aync, await을 이용해서 변경한 코드

```javascript
if (!validation.term && !validation.desc && !validation.exam) {
	const updateEvent = async () => {
		await dispatch(
			updateTermsFB(this_term.id, {
				term: term,
				desc: description,
				example: example,
				done: this_term.done,
			})
		);
		navigate("/");
	}
	updateEvent();
}
```
이렇게 변경할 경우 dispatch된 액션 크리에이터의 반환값인 함수가 리턴되면 그 후에 navigate가 실행될것이라고 생각했는데
그래도 navigate가 먼저 적용되었습니다. 

 <br/>

### action creator가 작성된 reducer 파일에서 적용해야 할 것 같아서 다시 수정

```javascript
if (!validation.term && !validation.desc && !validation.exam) {
	dispatch(
		updateTermsFB(this_term.id, {
			term: term,
			desc: description,
			example: example,
			done: this_term.done,
		})
	);
}
```
컴포넌트 파일에는 위와같이 수정하고,

```javascript
export const createTermsFB = (new_item) => { // 등록하기
  return async function(dispatch){
    const docRef = await addDoc(collection(db, 'terms'), new_item)
    const _new = await getDoc(docRef);
    const new_term = {...new_item, id: _new.id};
    await dispatch(createTerms(new_term));
    window.location.href = '/';
  }
}

export const updateTermsFB = (id, new_item) => { // 수정하기
  return async function(dispatch){
    const docRef = doc(db, 'terms', id);
    const prevDone = (await getDoc(docRef)).data().done;
    await updateDoc(docRef, {...new_item});
    await dispatch(updateTerms(id, new_item));
    // 공부 완료 상태만 변경됐을 경우에는 메인으로 이동하는 스크립트 작동하지 않도록 분기 처리
    if(prevDone === new_item.done) window.location.href = '/'; 
  }
}
```
등록하기/수정하기 액션을 실행시키는 dispatch 요청에 await을 추가한 뒤, 페이지 주소를 메인으로 이동시키는 스크립트를 추가하니 update/create가 먼저 실행된 뒤에 메인으로 넘어가서 정상적으로 작동하는것을 확인했습니다.

<br/>

## 질문
위와 같이 reducer 파일에서 데이터 업데이트 및 변경하는 작업을 진행하는 dispatch 요청 뒤에 페이지를 이동시키도록 하면 되는건가요?
매니저님께서 수요일에 게더 순회 하실 때 동기/비동기에 대해서 설명해주셨고 특정 이벤트가 처리된 뒤에 alert을 발생시키고 싶으면 그 이벤트가 작성된 곳에서 async, await을 사용해야 한다고 하셔서 거기서 힌트를 얻었는데 이렇게 하는게 맞을까요?!

그리고 뭔가 navigate 같은 리액션 언어가 아닌 쌩(?) 자바스크립트 언어인 window.location.href 를 사용해도 되는건지..궁금합니다!

**Comment by jihyunan-dev** [comment]
하연님의 시도 너무너무 좋습니다👏🏻👏🏻👏🏻
접근 방향이 제가 생각하는 방향과 같고, 어떻게해서든 해당 문제를 해결하셨다는 점에서 정말 박수를 보냅니다.

1) 위와 같이 reducer 파일에서 데이터 업데이트 및 변경하는 작업을 진행하는 dispatch 요청 뒤에 페이지를 이동시키도록 하면 되는건가요?
=> 네 맞습니다!  데이터가 파이어스토어 내에서 완전히 처리되어 response가 도착한 뒤 페이지를 이동한다면 원래 의도했던 바처럼 동작하게 될겁니다:)
다만 reducer파일보다는 redux module이라고 하는 편이 조금 더 명확할 것 같은 점 조심스럽게 말씀드립니다!

2) navigate 같은 리액션 언어가 아닌 쌩(?) 자바스크립트 언어인 window.location.href 를 사용해도 되는건지..궁금합니다!
=> 이 점은 지금 하고 계신 프로젝트가 SPA(single page application)이기 때문에 지양하시는 것이 좋습니다. 
SPA는 하연님이 만드신 모든 리액트 프로젝트의 코드를 최초 페이지 진입 시에 모두 다운받습니다. 
`react-router-dom`으로 페이지를 나누긴했지만, 어떤 페이지로 진입하셔도 모든 페이지의 js코드를 다 받게 됩니다. 대신 그 이후에는 다운받아야 할 js파일이 없기 때문에 빠르게 변화 반영 및 페이지 진입이 가능합니다.
`react-route-dom`에서 제공하는 `navigate` 역시 다운받아온 js 내에서 이동하는 것이지 `refresh` 하는 개념은 아닙니다.
그렇다면 `window.location.href`는 어떨까요? 
`window.location.href`는 `refresh` 됩니다. 처음 사이트에 진입했을 때처럼 모든 JS코드를 받아오게 됩니다.
그래서 지금은 프로젝트가 작아서 통째로 받아와도 빨리 렌더가 가능하지만, 만약 프로젝트가 매우 커지게 된다면 페이지 이동을 할 때마다 엄청난 양의 코드를 받아와서 느릴 수밖에 없는 상황이 될 것으로 예상됩니다.

thunk 함수 내에서 라우터를 연동하는 방법은 https://github.com/remix-run/react-router/issues/8264#issuecomment-991271554 를 참고하시면 좋습니다.
기존 `react-router-dom v5`에서는 [velopert-thunk에서 라우터 연동하기](https://react.vlpt.us/redux-middleware/07-router-with-thunk.html) 를 참고하시면 되었는데, v6의 코드가 변경되어 사용은 어렵습니다.
그래서 개념은 velopert 링크를 통해 이해하시고 위 github링크를 활용하시면 좋을 듯 합니다!

해당 내용 말고도 방법은 찾을 수는 있겠으나 위 방법이 가장 간단해 보입니다:)

답변이 되었으면 좋겠습니다ㅎㅎ 
일주일 동안 고생 많으셨고, 마지막 주특기 주차도 화이팅입니다😊😊
그리고 단어장 페이지 너무 예뻐요..💕

---
추가로 개발자 도구 - network 탭 - JS를 누른채로 페이지를 이동해보시면 어느 시점에 js를 받아오는지 확인하실 수 있으실거에요! 한 번 해보시길 추천드립니다:)
